-- Placeholder reconciling local migration history with the remote database.
--
-- Version 20260830000000 is recorded as applied in the remote
-- supabase_migrations.schema_migrations table but has no file in this repo —
-- it was applied out-of-band, which CONTEXT.md documents as this project's
-- normal history (the QBank tables and several functions were created in the
-- Supabase dashboard before migrations existed).
--
-- The CLI refuses `db push` while any remote version is missing locally, and
-- both alternatives it suggests are worse than this file: `migration repair
-- --status reverted` would record a lie about what is applied, and `db pull`
-- would dump a full schema snapshot over a repo that is additive-only by
-- convention.
--
-- This file is intentionally empty of DDL. The version is already in the remote
-- history table, so it is never executed against the remote database; it exists
-- only so the histories line up and later migrations can be pushed.
